version: '3.10'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 
      "python notifications/manage.py migrate && python notifications/manage.py runserver 0.0.0.0:9000"
    ports:
      - 8000:9000
    env_file:
      - ./notifications/core/.env
    depends_on:
      - redis
    volumes:
      - .:/Notifications
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure
    env_file:
      - ./notifications/core/.env
  redis:
    image: redis:alpine
    restart: always
    command: redis-server
  celery:
    build: .
    command: bash -c
      "cd notifications && python -m celery -A core worker -l info"
    depends_on:
      - redis
  celery-beat:
    build: .
    command: bash -c
      "cd notifications && celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - postgres
    env_file:
      - ./notifications/core/.env
