version: '3.10'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 
      "python notifications/manage.py migrate && python notifications/manage.py runserver 0.0.0.0:8000"
    ports:
      - 1337:8000
    env_file:
      - ./notifications/core/.env
    depends_on:
      - redis
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure
  redis:
    image: redis:alpine
    restart: always
    command: redis-server
  celery:
    build: .
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: bash -c
      "cd notifications && python -m celery -A core worker -l info"
    depends_on:
      - redis
  celery-beat:
    build: .
    command: bash -c
      "cd notifications && celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - postgres
    env_file:
      - notifications/core/.env
